### ISSUE TITLE
I can not see the name of the authenticated neither the session id in access.log

### ISSUE THREAD

**Issue by rdelatorrea07** [mikkolehtisalo/mod_gllog#3]
Hi,

Great job, I can intall mod_gllog!!
You wrote an comment but I did not realize that the thread was closed. You wrote an comment but I did not realize that the thread was closed.So I have decided to open a new problem.

Now I have a new problem, the results look like the following:

192.168.100.4 - - [03/Mar/2016:13:13:56 +0100] "GET /a/connection/available HTTP/1.1" 200 458 "https://192.168.100.179/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" "-" "-" "invalid"
192.168.100.4 - - [03/Mar/2016:13:18:35 +0100] "POST /a/metrics/205/1qenj1g1/xhr?t=1457007401883 HTTP/1.1" 200 1129 "https://192.168.100.179/gettingstarted" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" "-" "-" "invalid"
192.168.100.4 - - [03/Mar/2016:13:13:54 +0100] "GET /assets/fonts/OpenSans-Light-webfont.eot? HTTP/1.1" 304 197 "https://192.168.100.179/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" "-" "-" "invalid"
192.168.100.4 - - [03/Mar/2016:13:13:56 +0100] "GET /a/connection/available HTTP/1.1" 200 458 "https://192.168.100.179/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" "-" "-" "invalid"

I can not see the name of the authenticated neither the session id. This fields are blank ("-" "-").

Please, Can you help me?

Thanks you very much.

Regards.

**Comment by mikkolehtisalo** [comment]
Are you testing with 2.x?

It seems 2.x has very different scheme for request authentication, and currently there is no working solution for producing audit logs. You might want to follow issue [#1815](https://github.com/Graylog2/graylog2-server/issues/1815).

**Comment by rdelatorrea07** [comment]
Hello,
No, I have installed Graylog v1.3.3 and Apache 2.2.29 on CentOS 6.5.
I do not understand why token = NULL. It is the cause that the variables are displayed with the values ​​that are initialized ;
char \* username = "- " ;
char \* sessionid = "- " ;
char \* SignatureStatus = " invalid" ;

Perhaps, you can solve this problem.
Thanks for your answer
Regards!

**Comment by mikkolehtisalo** [comment]
Okay. Luckily there is debug logging in place. Find the LogLevel configuration stanza from the httpd.conf or similar, switch it to debug, and restart httpd. The error log for your virtualhost / server should contain more information about the problem!

**Comment by rdelatorrea07** [comment]
Good morning,
I have changed the LogLevel to debug in httpd.conf, but the problem does not solve.
My error log contains the following information:

[Tue Mar 08 09:28:25 2016] [info] Subsequent (No.37) HTTPS request received for child 204 (server 192.168.100.179:443)
[Tue Mar 08 09:28:25 2016] [info] Subsequent (No.4) HTTPS request received for child 141 (server 192.168.100.179:443)
[Tue Mar 08 09:28:25 2016] [debug] mod_proxy_http.c(56): proxy: HTTP: canonicalising URL //192.168.100.179:9000/a/metrics/734/y11hmded/xhr_send
[Tue Mar 08 09:28:25 2016] [debug] mod_proxy_http.c(56): proxy: HTTP: canonicalising URL //192.168.100.179:9000/a/metrics/734/y11hmded/xhr
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(1516): [client 192.168.100.4] proxy: http: found worker http://192.168.100.179:9000/ for http://192.168.100.179:9000/a/metrics/734/y11hmded/xhr_send?t=1457425589520, referer: https://192.168.100.179/
[Tue Mar 08 09:28:25 2016] [debug] mod_proxy.c(1036): Running scheme http handler (attempt 0)
[Tue Mar 08 09:28:25 2016] [debug] mod_proxy_http.c(1995): proxy: HTTP: serving URL http://192.168.100.179:9000/a/metrics/734/y11hmded/xhr_send?t=1457425589520
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(1516): [client 192.168.100.4] proxy: http: found worker http://192.168.100.179:9000/ for http://192.168.100.179:9000/a/metrics/734/y11hmded/xhr?t=1457425589521, referer: https://192.168.100.179/
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(2022): proxy: HTTP: has acquired connection for (192.168.100.179)
[Tue Mar 08 09:28:25 2016] [debug] mod_proxy.c(1036): Running scheme http handler (attempt 0)
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(2078): proxy: connecting http://192.168.100.179:9000/a/metrics/734/y11hmded/xhr_send?t=1457425589520 to 192.168.100.179:9000
[Tue Mar 08 09:28:25 2016] [debug] mod_proxy_http.c(1995): proxy: HTTP: serving URL http://192.168.100.179:9000/a/metrics/734/y11hmded/xhr?t=1457425589521
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(2236): proxy: connected /a/metrics/734/y11hmded/xhr_send?t=1457425589520 to 192.168.100.179:9000
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(2022): proxy: HTTP: has acquired connection for (192.168.100.179)
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(2078): proxy: connecting http://192.168.100.179:9000/a/metrics/734/y11hmded/xhr?t=1457425589521 to 192.168.100.179:9000
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(2236): proxy: connected /a/metrics/734/y11hmded/xhr?t=1457425589521 to 192.168.100.179:9000
[Tue Mar 08 09:28:25 2016] [debug] mod_proxy_http.c(1755): proxy: start body send
[Tue Mar 08 09:28:25 2016] [debug] mod_headers.c(756): headers: ap_headers_output_filter()
[Tue Mar 08 09:28:25 2016] [debug] mod_proxy_http.c(1869): proxy: header only
[Tue Mar 08 09:28:25 2016] [debug] mod_headers.c(756): headers: ap_headers_output_filter()
[Tue Mar 08 09:28:25 2016] [debug] proxy_util.c(2040): proxy: HTTP: has released connection for (192.168.100.179)
**[Tue Mar 08 09:28:25 2016] [debug] mod_gllog.c(161): Cookie sent by client: PLAY_SESSION=b2c44e2df26ab86fd7e6bb279f611c7dea79d2d7-sessionid=9bf15d57d1c8f2a80a9e146409645d491e6d9e2a412724bd294f62b3ce3c4de84c8c65dc226b90e01d490654cbaccdf0
[Tue Mar 08 09:28:25 2016] [debug] mod_gllog.c(190): Received signature: b2c44e2df26ab86fd7e6bb279f611c7dea79d2d7 sessionid: 9bf15d57d1c8f2a80a9e146409645d491e6d9e2a412724bd294f62b3ce3c4de84c8c65dc226b90e01d490654cbaccdf0
[Tue Mar 08 09:28:25 2016] [debug] mod_gllog.c(102): Hex decoded: \x9b\xf1]W\xd1\xc8\xf2\xa8\n\x9e\x14d\td]I\x1em\x9e*A'$\xbd)Ob\xb3\xce<M\xe8L\x8ce\xdc"k\x90\xe0\x1dI\x06T\xcb\xac\xcd\xf0 (len=48)
[Tue Mar 08 09:28:25 2016] [debug] mod_gllog.c(138): Decrypted: \xa6P_\xb1\xc4w\xf8\xe1\xc5\xb0\xe9_\x93\x89\x17\xceW0V\x97\!"T\xce_K7\xa7\xe5U\xe1W0V\x97\!"T\xce_K7\xa7\xe5U\xe1 (len=48)
[Tue Mar 08 09:28:25 2016] [debug] mod_gllog.c(73): Generated signature dc1dca8af6c74a316a337fde2a1ec02654a49562, original b2c44e2df26ab86fd7e6bb279f611c7dea79d2d7
[Tue Mar 08 09:28:25 2016] [debug] mod_gllog.c(54): Setting notes username: - sessionid: - validity: invalid**
Perhaps this information is a clue for solve the ploblem.
Thank you very much.
Regards

**Comment by mikkolehtisalo** [comment]
The most probable cause is that your GlLogKey is incorrect.

**Comment by rdelatorrea07** [comment]
Hello,
I do not understand you. How can I solve this ?
Can you help me, please? 

Regards!

**Comment by mikkolehtisalo** [comment]
It is hard to help when the setups are different, but basically this is what you need to do. You can probably find the correct file with something like

```
find / -type f -name *.conf* -exec grep -l application.secret {} \;
```

and you want the configuration file for the web component. Mine on 1.3 OVA is

```
/opt/graylog/conf/graylog-web-interface.conf
```

from that file you want to take the application.secret, for example

```
application.secret = "6ba8e9136dc8e8b1d17ab89307b29dffe23ed4c84ee4b0cbeea60be2eea28188c2a43c1ec3aaaac00f7ef45a1d6ac2514a2cdb7b4453fb90fd0595d1a1b106e4"
```

and use it in configuring the Apache module, for example

```
<VirtualHost *:80>
        GlLogKey "6ba8e9136dc8e8b1d17ab89307b29dffe23ed4c84ee4b0cbeea60be2eea28188c2a43c1ec3aaaac00f7ef45a1d6ac2514a2cdb7b4453fb90fd0595d1a1b106e4"
</VirtualHost>
```

**Comment by rdelatorrea07** [comment]
Great job!, gllog works.
For future versions, I think it would be interesting to include users register with failed attempts
Thank you very much for your attention.
Regards.
